In [1]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!pip install kagglehub

In [3]:
import kagglehub

path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

print("Dataset location:", path)

Using Colab cache for faster access to the 'new-plant-diseases-dataset' dataset.
Dataset location: /kaggle/input/new-plant-diseases-dataset


In [4]:
import os

print(os.listdir(path))

['New Plant Diseases Dataset(Augmented)', 'new plant diseases dataset(augmented)', 'test']


In [5]:
base_dir = path + "/New Plant Diseases Dataset(Augmented)"

In [7]:
print(os.listdir(base_dir))

['New Plant Diseases Dataset(Augmented)']


In [8]:
import os

base_dir = path + "/New Plant Diseases Dataset(Augmented)"
print(os.listdir(base_dir))

['New Plant Diseases Dataset(Augmented)']


In [9]:
import os

base_dir = path + "/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)"

print(os.listdir(base_dir))

['valid', 'train']


In [11]:
import os

train_dir = None
val_dir = None
test_dir = None

for root, dirs, files in os.walk(path):
    if "train" in dirs and "valid" in dirs:
        train_dir = os.path.join(root, "train")
        val_dir = os.path.join(root, "valid")

    if "test" in dirs:
        test_dir = os.path.join(root, "test")

print(train_dir)
print(val_dir)
print(test_dir)

/kaggle/input/new-plant-diseases-dataset/new plant diseases dataset(augmented)/New Plant Diseases Dataset(Augmented)/train
/kaggle/input/new-plant-diseases-dataset/new plant diseases dataset(augmented)/New Plant Diseases Dataset(Augmented)/valid
/kaggle/input/new-plant-diseases-dataset/test/test


## Importing Library

In [12]:
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

## Data Presrocessing

Training Image Processing

In [22]:
path_ke_folder_train = '/kaggle/input/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train'
training_set = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


In [15]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Validation Image processing

In [27]:
path_ke_folder_train = '/kaggle/input/new-plant-diseases-dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid'
validation_set = tf.keras.utils.image_dataset_from_directory(
    val_dir,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    format="tf",
    verbose=True,
)

Found 17572 files belonging to 38 classes.


To avoid Overshooting

1. Choose small learning rate default 0.001 we are taking 0.0001
2. There may be chance of Underfitting, so increase number of neuron
3. Add more Convolution layer to extract more feature from images there may be possibil


In [28]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[101.5   83.5   79.5 ]
   [106.75  88.75  84.75]
   [106.5   88.5   86.5 ]
   ...
   [208.25 197.25 205.25]
   [194.5  183.5  191.5 ]
   [188.5  177.5  185.5 ]]

  [[107.25  89.25  85.25]
   [117.    99.    95.  ]
   [109.75  91.75  89.75]
   ...
   [195.75 184.75 192.75]
   [203.75 192.75 200.75]
   [199.5  188.5  196.5 ]]

  [[105.5   87.5   85.5 ]
   [108.75  90.75  88.75]
   [106.25  88.25  86.25]
   ...
   [196.75 185.75 193.75]
   [206.   195.   203.  ]
   [196.   185.   193.  ]]

  ...

  [[ 97.75  78.75  80.75]
   [ 91.75  72.75  74.75]
   [ 96.25  77.25  79.25]
   ...
   [ 92.5   99.    26.25]
   [149.75 149.    96.25]
   [148.75 140.25 127.5 ]]

  [[ 98.25  79.25  81.25]
   [100.75  81.75  83.75]
   [ 98.75  79.75  81.75]
   ...
   [120.5  120.25  45.75]
   [124.25 117.    60.  ]
   [155.75 139.   124.75]]

  [[ 95.25  76.25  78.25]
   [ 81.5   62.5   64.5 ]
   [ 97.5   78.5   80.5 ]
   ...
   [ 91.5   82.5   14.25]
   [120.5  104.75  52.5 ]
   [157.5  132.   12

# Building Models


In [29]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [30]:
model = Sequential()

In [31]:
## Building Convolution Layer

In [32]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [33]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [34]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [35]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [36]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [37]:
model.add(Dropout(0.25)) # To avoid Overfitting

In [38]:
model.add(Flatten())

In [39]:
model.add(Dense(units=1500,activation='relu'))

In [40]:
model.add(Dropout(0.4))

In [41]:
#Output Layer
model.add(Dense(units=38,activation='softmax'))

# Compiling Model

In [44]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [45]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

## Model Training

In [46]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 260s 110ms/step - accuracy: 0.6007 - loss: 1.3586 - val_accuracy: 0.8323 - val_loss: 0.5292
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 145s 66ms/step - accuracy: 0.8609 - loss: 0.4413 - val_accuracy: 0.8976 - val_loss: 0.3191
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 143s 65ms/step - accuracy: 0.9129 - loss: 0.2677 - val_accuracy: 0.9322 - val_loss: 0.2118
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 143s 65ms/step - accuracy: 0.9403 - loss: 0.1858 - val_accuracy: 0.9437 - val_loss: 0.1738
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 204s 66ms/step - accuracy: 0.9546 - loss: 0.1415 - val_accuracy: 0.9550 - val_loss: 0.1363
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 145s 66ms/step - accuracy: 0.9661 - loss: 0.1039 - val_accuracy: 0.9612 - val_loss: 0.1266
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 142s 65ms/step - accuracy: 0.9705 - loss: 0.0913 - val_accuracy: 0.9659 - val_loss: 0.1214
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 143s 65ms/step - accuracy: